server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  devtools:
    restart:
      enabled: true  #设置开启热部署，false即不开启热部署
      #additional-paths: src/main/java #指定热部署的目录
  #配置mail
  mail:
    host: smtp.qq.com
    username: *****
    password: *****

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射(根据类名/属性名，有两种驼峰)
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

#目前没用到mybatis，要用的话这里指定XxxMapper.xml配置文件位置
mybatis:
  mapper-locations: classpath:/mapper/*.xml

#这里定义的是图片的位置,@Value("${reggie.path}")绑定变量使用
reggie:
  path: "D:\\My program\\My Java\\Maven\\Reggie_course\\riggie_upload_pictures\\"